# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: build
  displayName: Build
  strategy:
    matrix:
      linux:
        image: 'ubuntu-latest'
      windows:
        image: 'windows-latest'
    maxParallel: 10
  pool:
    vmImage: $(image)
  workspace:
    clean: all

  steps:

  # Set the correct toolchain
  - script: |
      rustup default stable
      rustup update stable
    displayName: "Set correct Rust version"

  # Install components
  - script: |
      rustup component add rustfmt --toolchain stable
      rustup component add clippy --toolchain stable

  # Output rust environment
  - script: |
      rustc --version
      cargo --version
      rustup --version
    displayName: Check installed rust version

  # Format check
  - script: cargo fmt --all -- --check
    displayName: Check formatting

  # Clippy check
  - script: cargo clippy -- -D warnings
    displayName: Check Clippy

  # Build and test
  - script: cargo test
    displayName: Build and Test